function valid = is_valid_block_header(header)
% 判断block header是否合规

if isempty(header.WFWords)
    valid = [];
else
    valid = ismember(header.Type, [1 4 5]) && ...
        (header.UpperTimestamp >= 0) && ...
        (header.TimeStamp >= 0) && ...
        (header.Channel >= 0) && ...
        (header.Unit >= 0) && ...
        ismember(header.NumWF, [0 1]) && ...
        (0 <= header.WFWords && header.WFWords <= 32);
end

end